USE [master]
GO
/****** Object:  Database [EXTERNAS_LBD]    Script Date: 25/02/2020 12:58:03 a. m. ******/
CREATE DATABASE [EXTERNAS_LBD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EXTERNAS_LBD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\EXTERNAS_LBD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EXTERNAS_LBD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\EXTERNAS_LBD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [EXTERNAS_LBD] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EXTERNAS_LBD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EXTERNAS_LBD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EXTERNAS_LBD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EXTERNAS_LBD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EXTERNAS_LBD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EXTERNAS_LBD] SET ARITHABORT OFF 
GO
ALTER DATABASE [EXTERNAS_LBD] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [EXTERNAS_LBD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [EXTERNAS_LBD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EXTERNAS_LBD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EXTERNAS_LBD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [EXTERNAS_LBD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EXTERNAS_LBD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EXTERNAS_LBD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EXTERNAS_LBD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EXTERNAS_LBD] SET  ENABLE_BROKER 
GO
ALTER DATABASE [EXTERNAS_LBD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EXTERNAS_LBD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EXTERNAS_LBD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [EXTERNAS_LBD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [EXTERNAS_LBD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EXTERNAS_LBD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [EXTERNAS_LBD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [EXTERNAS_LBD] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [EXTERNAS_LBD] SET  MULTI_USER 
GO
ALTER DATABASE [EXTERNAS_LBD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EXTERNAS_LBD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [EXTERNAS_LBD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [EXTERNAS_LBD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [EXTERNAS_LBD] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [EXTERNAS_LBD] SET QUERY_STORE = OFF
GO
ALTER DATABASE [EXTERNAS_LBD] SET  READ_WRITE 
GO
